name: flutterby
description: learning flutter

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
